txgh: &txgh
  before_install: gem install bundler -v 1.12.5
  install: cd txgh; bundle install --no-deployment --jobs 3 --retry 3; cd ..
  script: cd txgh && bundle exec rspec && cd ..
  env: NAME=txgh

server: &server
  before_install: gem install bundler -v 1.12.5
  install: cd server; bundle install --no-deployment --jobs 3 --retry 3; cd ..
  script: cd server && bundle exec rake spec:full && cd ..
  env: NAME=txgh-server

sudo: false
language: ruby
matrix:
  include:
    - rvm: 2.1.6
      <<: *txgh
    - rvm: 2.1.6
      <<: *server
    - rvm: 2.2.5
      <<: *txgh
    - rvm: 2.2.5
      <<: *server
