txgh: &txgh
  before_install: gem install bundler -v 2.2.5
  install: cd txgh; bundle install --no-deployment --jobs 3 --retry 3; cd ..
  script: cd txgh && bundle exec rspec && cd ..
  env: NAME=txgh

server: &server
  before_install: gem install bundler -v 2.2.5
  install: cd server; bundle install --no-deployment --jobs 3 --retry 3; cd ..
  script: cd server && bundle exec rake spec:full && cd ..
  env: NAME=txgh-server

queue: &queue
  before_install: gem install bundler -v 2.2.5
  install: cd queue; bundle install --no-deployment --jobs 3 --retry 3; cd ..
  script: cd queue && bundle exec rspec && cd ..
  env: NAME=txgh-queue

sudo: false
language: ruby
matrix:
  include:
    - rvm: 2.5.8
      <<: *txgh
    - rvm: 2.5.8
      <<: *server
    - rvm: 2.5.8
      <<: *queue

    - rvm: 2.6.0
      <<: *txgh
    - rvm: 2.6.0
      <<: *server
    - rvm: 2.6.0
      <<: *queue
